name: PushGitlab

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
      env: 
        token: ${{ secrets.GITLAB_ACCESS_TOKEN }}

    - name: Push To Gitlab
      run: |
        echo Starting to push repo to gitlab
        git config user.name "DOCENCIA"
        git config user.email "docencia@mmae.cl"
        git remote set-url origin "https://oauth2:${token}@gitlab.com/chuang_/jskara-web.git"
        git push origin main
